### PR TITLE
refactor(picker): heavy refactoring of the picker logic and more 

### LINKED ISSUE #8: [BUG] Performance Issue
**Describe the bug**
This is not the most clear bug report but have you noticed any strange lag/performance hiccups since the introduction of a lot of the changes? I added a lot of changes at once so  I didn't get a good feel for where/when it started. I did notice that you commented out the format-tab-title code with a comment of performance issues. However, even with that commented out I noticed a strange lag with certain things. 

I think it is most noticeable when saving changes to the config.

**To Reproduce**
1. Go to any file in the config and make an edit or comment.
2. Save the changes.
3. Let Wezterm hot reload the changes to the config.
4. On Windows I get a lot of window resizing/flashing when the config is changed/reloaded.

**Expected behavior**
I don't think I ever recall having anything like this in the past when applying changes/config overrides/etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Wezterm Nightly

### PR DESCRIPTION
**Pull request by sravioli**
## Proposed changes

Heavy refactoring of the picker class.

Features:

- Creating a new picker is now easier (most basic picker):
  
  ~~~lua
  local Picker = require("utils").class.picker

  return Picker.new {
    title = "Font size picker",
    subdir = "font-sizes",
  }
  ~~~

- While creating a picker is easier, the clas still offers control. The `build` allows the user to dynamically build the `choices` table.  For example:

  Colorscheme picker. Each colorscheme palette is shown before its name

- adding a new picker is easy! create a file for the picker, then create a folder in `./picker/assets/` and add it's assets into the newly created folder.

Fixes: 

- grouped pickers and their assets to single folder.
- `Utils.Fn.FileSystem.read_dir()` (fs) does not create many windows popup on Windows (caused by `io.popen()`
- implemented caching in `wezterm.GLOBAL` for `fs.read_dir()` and two other functions (`fs.home()`, `fs.platform()`)
- fixes #8 

TODO:

- [x] re-implement the font-picker that @akthe-at implemented for the previous picker class
- [ ] [NOT POSSIBLE] add possibility to also pick builtins colorschemes (does not have to impact performance)
- [x] add a bit more custom themes to pick from (all the builtins themes that have the `tab_bar` field)

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask._

- [x] I have read the [CONTRIBUTING](https://github.com/sravioli/wezterm/blob/main/.github/CONTRIBUTING.md) doc
- [ ] I have added the necessary documentation (if appropriate)

## Further comments

Big thanks to @akthe-at for ideas and contributions to the refactor.

### CODE REVIEW

**Comment by akthe-at** [comment]
I don't understand why this[ commit ](https://github.com/sravioli/wezterm/commit/15aa56d381d000aeb028b63519478bff9daa8fa4) brought back the spamming creation of external cmd prompt shells :(

**Comment by sravioli** [comment]
> I don't understand why this[ commit ](https://github.com/sravioli/wezterm/commit/15aa56d381d000aeb028b63519478bff9daa8fa4) brought back the spamming creation of external cmd prompt shells :(

Aww dang it. I don't understand.. The logic should be the same...

I'll have a look tomorrow on Win11

**Comment by akthe-at** [comment]
Does Tokyonight-storm cause errors for you at all? The other tokyonight variations do not.

**Comment by sravioli** [comment]
> Does Tokyonight-storm cause errors for you at all? The other tokyonight variations do not.

Yup, looks like an the id of that theme was wrong. Pushed the fix :)

**Pull request merged**
